
services:

  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=trueke
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5555:5432"

  client:
    container_name: client-pg
    image: 'dpage/pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "5050:80"